config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :actors

      resources :roles

      resources :directors

      resources :movies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "movies#index"
  resources :actors
  resources :roles
  resources :directors
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ApplicationRecord
  # Direct associations

  belongs_to :actor

  belongs_to :director

  belongs_to :movie

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    movie.to_s
  end
end

app/controllers/api/v1/roles_controller.rb
class Api::V1::RolesController < Api::V1::GraphitiController
  def index
    roles = RoleResource.all(params)
    respond_with(roles)
  end

  def show
    role = RoleResource.find(params)
    respond_with(role)
  end

  def create
    role = RoleResource.build(params)

    if role.save
      render jsonapi: role, status: :created
    else
      render jsonapi_errors: role
    end
  end

  def update
    role = RoleResource.find(params)

    if role.update_attributes
      render jsonapi: role
    else
      render jsonapi_errors: role
    end
  end

  def destroy
    role = RoleResource.find(params)

    if role.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: role
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[show edit update destroy]

  def index
    @q = Role.ransack(params[:q])
    @roles = @q.result(distinct: true).includes(:movie, :director,
                                                :actor).page(params[:page]).per(10)
  end

  def show; end

  def new
    @role = Role.new
  end

  def edit; end

  def create
    @role = Role.new(role_params)

    if @role.save
      message = "Role was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @role, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @role.update(role_params)
      redirect_to @role, notice: "Role was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @role.destroy
    message = "Role was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to roles_url, notice: message
    end
  end

  private

  def set_role
    @role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:movie_id, :actor_id, :director_id)
  end
end

app/views/roles/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Role #<%= role.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Movie</dt>
      <dd>
        <% if @role.movie.present? %>
          <%= link_to role.movie, role.movie %>
        <% end %>
      </dd>

      <dt>Actor</dt>
      <dd>
        <% if @role.actor.present? %>
          <%= link_to role.actor, role.actor %>
        <% end %>
      </dd>

      <dt>Director</dt>
      <dd>
        <% if @role.director.present? %>
          <%= link_to role.director, role.director %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back role, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_role_url(role), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to role, method: :delete, data: { confirm: "Do you really want to delete this role?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(role.updated_at) %> ago
  </div>
</div>

app/views/roles/_form.html.erb
<% was_validated = role.errors.any? %>

<%= form_with(model: role, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% movie_class = "form-control" %>
    <% movie_was_invalid = role.errors.include?(:movie) %>

    <% if was_validated %>
      <% if movie_was_invalid %>
        <% movie_class << " is-invalid" %>
      <% else %>
        <% movie_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :movie_id %>
    <%= f.collection_select :movie_id, Movie.all, :id, :to_s, {}, class: "form-control" %>
    <% if movie_was_invalid %>
      <% role.errors.full_messages_for(:movie).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% actor_class = "form-control" %>
    <% actor_was_invalid = role.errors.include?(:actor) %>

    <% if was_validated %>
      <% if actor_was_invalid %>
        <% actor_class << " is-invalid" %>
      <% else %>
        <% actor_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :actor_id %>
    <%= f.collection_select :actor_id, Actor.all, :id, :to_s, {}, class: "form-control" %>
    <% if actor_was_invalid %>
      <% role.errors.full_messages_for(:actor).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% director_class = "form-control" %>
    <% director_was_invalid = role.errors.include?(:director) %>

    <% if was_validated %>
      <% if director_was_invalid %>
        <% director_class << " is-invalid" %>
      <% else %>
        <% director_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :director_id %>
    <%= f.collection_select :director_id, Director.all, :id, :to_s, {}, class: "form-control" %>
    <% if director_was_invalid %>
      <% role.errors.full_messages_for(:director).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/roles/_list_item.html.erb
<%= link_to role, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= role %>
    <small class="text-muted">
      <%= time_ago_in_words(role.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/roles/_roles_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "roles_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :movie_title_cont, "Movie title contains" %>
    <%= f.text_field :movie_title_cont, :class => "form-control", :placeholder => "Movie title contains" %>
  </div>

  <div class="form-group">
    <%= f.label :director_name_cont, "Director name contains" %>
    <%= f.text_field :director_name_cont, :class => "form-control", :placeholder => "Director name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/roles" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#roles_filters">
  Show filters
</a>

app/views/roles/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Role #<%= @role.id %>
      </h2>

      <div class="card-body">
        <%= render "form", role: @role %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Roles

      <%= link_to new_role_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "roles/roles_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Roles

        <%= link_to new_role_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @roles, partial: "list_item", as: :role %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @roles, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/roles/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Role
      </h2>

      <div class="card-body">
        <%= render "form", role: @role %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/roles/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @role, partial: "card", as: :role %>
  </div>
</div>